apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-back.yaml
- deployment-front.yaml
- service-back.yaml
- service-front.yaml
- secrets.yaml

commonLabels:
  app.kubernetes.io/name: voicerag
  app.kubernetes.io/part-of: voicerag-platform

configMapGenerator:
- name: voicerag-config
  literals:
  - RUNNING_IN_PRODUCTION="false"