apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: azure-kv-secrets
    type: Opaque
    labels:
      environment: "dev"
    data:
    - objectName: AZURE-CLIENT-ID                   # name of the mounted content to sync. this could be the object name or object alias
      key: AZURE-CLIENT-ID
    - objectName: AZURE-CLIENT-SECRET                 # name of the mounted content to sync. this could be the object name or object alias
      key: AZURE-CLIENT-SECRET
    - objectName: AZURE-TENANT-ID               # name of the mounted content to sync. this could be the object name or object alias
      key: AZURE-TENANT-ID
    - objectName: AZURE-OPENAI-API-KEY                  # name of the mounted content to sync. this could be the object name or object alias
      key: AZURE-OPENAI-API-KEY 
    - objectName: AZURE-SEARCH-API-KEY                  # name of the mounted content to sync. this could be the object name or object alias
      key: AZURE-SEARCH-API-KEY
    - objectName: AZURE-OPENAI-ENDPOINT                  # name of the mounted content to sync. this could be the object name or object alias
      key: AZURE-OPENAI-ENDPOINT
    - objectName: AZURE-SEARCH-ENDPOINT                  # name of the mounted content to sync. this could be the object name or object alias
      key: AZURE-SEARCH-ENDPOINT
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${YOUR_CLIENT_ID} # Se debe cambiar por el ClientID propio
    keyvaultName: apprer # Se debe cambiar el nombre del AKV
    objects: |
      array:
        - |
          objectName: AZURE-CLIENT-ID
          objectType: secret
        - |
          objectName: AZURE-CLIENT-SECRET
          objectType: secret
        - |
          objectName: AZURE-TENANT-ID
          objectType: secret
        - |
          objectName: AZURE-OPENAI-ENDPOINT
          objectType: secret
        - |
          objectName: AZURE-SEARCH-ENDPOINT
          objectType: secret
    tenantId: ${YOUR_TENANT_ID} # Se debe cambiar por el tenantID propio.
