name: Build and Deploy VoiceRAG

on:
  push:
    branches: [ "main", "develop" ]
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: backend
  FRONTEND_IMAGE_NAME: frontend

  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker
      - name: Extract Docker metadata for Backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.BACKEND_IMAGE_NAME }}

      - name: Extract Docker metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.FRONTEND_IMAGE_NAME }}

      # Build and push Backend Docker image
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Frontend Docker image
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Scan Backend image for vulnerabilities
      - name: Run Trivy vulnerability scanner for Backend
        uses: aquasecurity/trivy-action@master
        if: github.event_name != 'pull_request'
        with:
          image-ref: ${{ steps.meta-backend.outputs.tags }}
          format: 'sarif'
          output: 'trivy-results-backend.sarif'

      # Scan Frontend image for vulnerabilities
      - name: Run Trivy vulnerability scanner for Frontend
        uses: aquasecurity/trivy-action@master
        if: github.event_name != 'pull_request'
        with:
          image-ref: ${{ steps.meta-frontend.outputs.tags }}
          format: 'sarif'
          output: 'trivy-results-frontend.sarif'

      - name: Trivy Summary
        if: always() && github.event_name != 'pull_request'
        run: |
          echo "## Trivy Scan Summary" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "trivy-results-backend.sarif" ]; then
            echo "### Backend Image" >> $GITHUB_STEP_SUMMARY
            ERRORS=$(jq '[.runs[0].results[] | select(.level == "error")] | length' trivy-results-backend.sarif)
            WARNINGS=$(jq '[.runs[0].results[] | select(.level == "warning")] | length' trivy-results-backend.sarif)
            NOTES=$(jq '[.runs[0].results[] | select(.level == "note")] | length' trivy-results-backend.sarif)
            echo "| Level | Count |" >> $GITHUB_STEP_SUMMARY
            echo "|:---|:---:|" >> $GITHUB_STEP_SUMMARY
            echo "| Errors (Critical, High) | $ERRORS |" >> $GITHUB_STEP_SUMMARY
            echo "| Warnings (Medium) | $WARNINGS |" >> $GITHUB_STEP_SUMMARY
            echo "| Notes (Low, Unknown) | $NOTES |" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f "trivy-results-frontend.sarif" ]; then
            echo "### Frontend Image" >> $GITHUB_STEP_SUMMARY
            ERRORS=$(jq '[.runs[0].results[] | select(.level == "error")] | length' trivy-results-frontend.sarif)
            WARNINGS=$(jq '[.runs[0].results[] | select(.level == "warning")] | length' trivy-results-frontend.sarif)
            NOTES=$(jq '[.runs[0].results[] | select(.level == "note")] | length' trivy-results-frontend.sarif)
            echo "| Level | Count |" >> $GITHUB_STEP_SUMMARY
            echo "|:---|:---:|" >> $GITHUB_STEP_SUMMARY
            echo "| Errors (Critical, High) | $ERRORS |" >> $GITHUB_STEP_SUMMARY
            echo "| Warnings (Medium) | $WARNINGS |" >> $GITHUB_STEP_SUMMARY
            echo "| Notes (Low, Unknown) | $NOTES |" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi